#!/bin/bash

export DOCKER_REPO_PREFIX=benmatselby

del_stopped(){
    local name=$1
    local state
    state=$(docker inspect --format "{{.State.Running}}" "$name" 2>/dev/null)

    if [[ "$state" == "false" ]]; then
    docker rm "$name"
    fi
}
dhagen() {
    docker run \
        --rm \
        -t \
        -eGITHUB_OWNER \
        -eGITHUB_TOKEN \
        -v "${HOME}/.benmatselby":/root/.benmatselby \
        ${DOCKER_REPO_PREFIX}/hagen "$@"
}
dfrost() {
    docker run \
        --rm \
        -t \
        -eAZURE_DEVOPS_ACCOUNT \
        -eAZURE_DEVOPS_PROJECT \
        -eAZURE_DEVOPS_TEAM \
        -eAZURE_DEVOPS_TOKEN \
        -eTRAVIS_CI_TOKEN \
        -eTRAVIS_CI_OWNER \
        -eJENKINS_URL \
        -eJENKINS_USERNAME \
        -eJENKINS_PASSWORD \
        -eJENKINS_VIEW \
        ${DOCKER_REPO_PREFIX}/frost "$@"
}
ddonny() {
    docker run \
        --rm \
        -t \
        -eAZURE_DEVOPS_ACCOUNT \
        -eAZURE_DEVOPS_PROJECT \
        -eAZURE_DEVOPS_TEAM \
        -eAZURE_DEVOPS_TOKEN \
        ${DOCKER_REPO_PREFIX}/donny "$@"
}
dwalter() {
     docker run \
        --rm \
        -t \
        -eJIRA_TOKEN \
        -eJIRA_URL \
        -eJIRA_USERNAME \
        -v "${HOME}/.benmatselby":/root/.benmatselby \
        ${DOCKER_REPO_PREFIX}/walter "$@"
}

###
# Jess related tooling
##

# https://github.com/genuinetools/pepper
pepper() {
    docker run --rm -t \
        -eGITHUB_TOKEN \
        jess/pepper "$@"
}

# https://github.com/genuinetools/udict
udict() {
    docker run --rm -t jess/udict "$@"
}
