aliases:
    prc: pr create
    prcf: pr create --fill
    pramr: pr merge --auto -d -r
    prama: pr merge --auto -d -m
    rv: repo view -w
    mpr: repo list --visibility public --no-archived --source -L 50
    mtr: repo list prolific-oss --topic team-incubator
version: "1"
